import Head from 'next/head'
import Link from "next/link"

import styles from '../../styles/Home.module.css'

const index = () => {
  return (
    <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Blog index</h1>
        <br/>
        <Link href="./blog/fotografia-noworodkowa/">Blog. Fotografia noworodkowa</Link>
        <Link href="./blog/fotografia-dzieci/">Blog. Fotografia dzieci</Link>
        <Link href="./blog/fotografia-slubna/">Blog. Fotografia ślubna</Link>
        <Link href="./blog/pozostale-wpisy/">Blog. Pozostałe wpisy</Link>
        <Link href="./">Home</Link>
        <br/><br/>
        <Link href="./blog/post/2021/07/warsztaty-fotografii-noworodkowej-katowice-2021/">Warsztaty fotografii noworodkowej. Katowice 2021</Link>
        <Link href="http://localhost:3000/2021/07/warsztaty-fotografii-noworodkowej-katowice-2021/">old link</Link>
      </main>

        <footer className={styles.footer}>
        
        </footer>
    </div>  
  )
}

export default index